remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: kenneally.dev
description: Digital garden & client staging area
# show_downloads: true | false # set to true if you want to offer downloads of the repo as zip & tar, plus a button link to the repo
# google_analytics: # Your Google Analytics tracking ID
logo: logo.svg  # uses the theme file as we don't have it in here, yet
