remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Dylan Kenneally
description: Experimenting with Jekyll
# show_downloads: true | false # set to true if you want to offer downloads of the repo as zip & tar, plus a button link to the repo
# google_analytics: # Your Google Analytics tracking ID
logo: /assets/img/logo.png  # uses the theme file as we don't have it in here, yet
