remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Dylan Kenneally - Developer
description: Experimenting with Jekyll
# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
